//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainstormingApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrainstormingApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your answer..
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreatePage {
            get {
                return ResourceManager.GetString("CreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all items.
        /// </summary>
        internal static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all but favorite items.
        /// </summary>
        internal static string DeleteNonfavorite {
            get {
                return ResourceManager.GetString("DeleteNonfavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe your problem..
        /// </summary>
        internal static string DescribeProblem {
            get {
                return ResourceManager.GetString("DescribeProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit or delete.
        /// </summary>
        internal static string EditDeletePage {
            get {
                return ResourceManager.GetString("EditDeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter five words.
        /// </summary>
        internal static string EnterFive {
            get {
                return ResourceManager.GetString("EnterFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter idea name.
        /// </summary>
        internal static string EnterIdea {
            get {
                return ResourceManager.GetString("EnterIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five why&apos;s.
        /// </summary>
        internal static string FiveWhys {
            get {
                return ResourceManager.GetString("FiveWhys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method will help you to generate ideas by going in depth with asking why five times before you get the actual idea..
        /// </summary>
        internal static string FiveWhysDescribe {
            get {
                return ResourceManager.GetString("FiveWhysDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea description.
        /// </summary>
        internal static string IdeaDescription {
            get {
                return ResourceManager.GetString("IdeaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea name.
        /// </summary>
        internal static string IdeaName {
            get {
                return ResourceManager.GetString("IdeaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mash up.
        /// </summary>
        internal static string MashUp {
            get {
                return ResourceManager.GetString("MashUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mash up will suggest two random ideas from your list and you should try to generate an idea which is combined from the original two.
        /// </summary>
        internal static string MashUpDescribe {
            get {
                return ResourceManager.GetString("MashUpDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need at least two ideas to use this method..
        /// </summary>
        internal static string MashUpNotEnough {
            get {
                return ResourceManager.GetString("MashUpNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        internal static string Methods {
            get {
                return ResourceManager.GetString("Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the new idea.
        /// </summary>
        internal static string NewIdeaName {
            get {
                return ResourceManager.GetString("NewIdeaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related words.
        /// </summary>
        internal static string RelatedWords {
            get {
                return ResourceManager.GetString("RelatedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this method, you will first think of any five words, related or unrelated to your topic. Then, you will generate ideas that are in any way linked to any of your words AND your project..
        /// </summary>
        internal static string RelatedWordsDescribe {
            get {
                return ResourceManager.GetString("RelatedWordsDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What idea does this give you?.
        /// </summary>
        internal static string WhatIdea {
            get {
                return ResourceManager.GetString("WhatIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why?.
        /// </summary>
        internal static string Why {
            get {
                return ResourceManager.GetString("Why", resourceCulture);
            }
        }
    }
}
